# Use root/example as user/password credentials
version: '3.8'
services:

    node:
      user: node
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - 3000:3000

      volumes:
        - ..:/Ito-ocashi-review:cached
        - /Ito-ocashi-review/node_modules
        - /Ito-ocashi-review/.next
      tty: true
